var a = 10;
var fname = "Raj Deep";
var result1 = true;
//a="Ravi";
var info = "Welcome";
info = false;
info = 200;
var b = 200;
var lname = "Ravi Kumar";
var result2 = false;
var id;
var fullname;
var result3;
id = 300;
fullname = "Ajay Kumar";
result3 = true;
console.log(a);
console.log(fname);
console.log(result1);
